#pragma once

#ifndef DICE_ROLLER_VERSION_HPP
#define DICE_ROLLER_VERSION_HPP

//
// Dice Roller Library Build Type
//

// Dice Roller Libray build type:
// 1 - Alpha
// 2 - Beta
// 3 - Release Candidate
// 4 - Release
#define DICE_ROLLER_LIB_BUILD_TYPE 1

#if DICE_ROLLER_LIB_BUILD_TYPE == 1
	#define DICE_ROLLER_LIB_BUILD_TYPE_ALPHA				// Dice Roller Library to compile with alpha features
#elif DICE_ROLLER_LIB_BUILD_TYPE == 2
	#define DICE_ROLLER_LIB_BUILD_TYPE_BETA					// Dice Roller Library to compile with beta features
#elif DICE_ROLLER_LIB_BUILD_TYPE == 3
	#define DICE_ROLLER_LIB_BUILD_TYPE_RELEASE_CANDIDATE	// Dice Roller Library to compile with release candidate features
#elif DICE_ROLLER_LIB_BUILD_TYPE == 4
	#define DICE_ROLLER_LIB_BUILD_TYPE_RELEASE				// Dice Roller Library to compile with release features
#else
	#error "No DiceRoller library build type is defined!"
#endif // !DICE_ROLLER_LIB_BUILD_TYPE

//
// Dice Roller Library Build:
//

#ifdef DICE_ROLLER_LIB_BUILD_TYPE_ALPHA
	#define DICE_ROLLER_LIB_VERSION_MAJOR_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_MINOR_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_PATCH_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_BUILD_NUMBER 0
	#define DICE_ROLLER_LIB_VERSION_BUILD_TYPE "alpha"
	#define DICE_ROLLER_LIB_VERSION_BUILD_TYPE_NUMBER 0
#endif // !DICE_ROLLER_LIB_BUILD_TYPE_ALPHA

#ifdef DICE_ROLLER_LIB_BUILD_TYPE_BETA
	#define DICE_ROLLER_LIB_VERSION_MAJOR_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_MINOR_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_PATCH_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_BUILD_NUMBER 0
	#define DICE_ROLLER_LIB_VERSION_BUILD_TYPE "beta"
	#define DICE_ROLLER_LIB_VERSION_BUILD_TYPE_NUMBER 0
#endif // !DICE_ROLLER_LIB_BUILD_TYPE_BETA

#ifdef DICE_ROLLER_LIB_BUILD_TYPE_RELEASE_CANDIDATE
	#define DICE_ROLLER_LIB_VERSION_MAJOR_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_MINOR_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_PATCH_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_BUILD_NUMBER 0
	#define DICE_ROLLER_LIB_VERSION_BUILD_TYPE "release candidate"
	#define DICE_ROLLER_LIB_VERSION_BUILD_TYPE_NUMBER 0
#endif // !DICE_ROLLER_LIB_BUILD_TYPE_RELEASE_CANDIDATE

#ifdef DICE_ROLLER_LIB_BUILD_TYPE_RELEASE
	#define DICE_ROLLER_LIB_VERSION_MAJOR_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_MINOR_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_PATCH_VERSION 0
	#define DICE_ROLLER_LIB_VERSION_BUILD_NUMBER 0
	#define DICE_ROLLER_LIB_VERSION_BUILD_TYPE "release"
	#define DICE_ROLLER_LIB_VERSION_BUILD_TYPE_NUMBER 0
#endif // !DICE_ROLLER_LIB_BUILD_TYPE_RELEASE

#endif // !DICE_ROLLER_VERSION_HPP